import React from 'react'; import {View,Text,Pressable,Image,StyleSheet,FlatList,ActivityIndicator} from 'react-native'; import {Ionicons} from '@expo/vector-icons'; import {colors,spacing,radii,typography} from '../theme'; import {Product} from '../data/products'; import {money} from '../utils'; import {useStore} from '../store/useStore';
export function Header({title,back,onBack}:{title?:string;back?:boolean;onBack?:()=>void}){return <View style={s.header}>{back?<Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={onBack}><Ionicons name="chevron-back" size={22} color={colors.ink}/></Pressable>:<Text style={s.logo}>ASHIANA</Text>}<Text style={s.headerTitle}>{title||''}</Text><View style={{width:24}}/></View>}
export function IconButton({icon,onPress,label}:{icon:any;onPress:()=>void;label:string}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={s.icon}><Ionicons name={icon} size={20} color={colors.ink}/></Pressable>}
export function ProductImage({uri,style}:{uri:string;style?:any}){return <Image source={{uri}} style={[{backgroundColor:colors.placeholder},style]} resizeMode="cover" accessibilityRole="image"/>}
export function SectionHeader({title,action,onAction}:{title:string;action?:string;onAction?:()=>void}){return <View style={s.sectionHead}><Text style={s.h2}>{title}</Text>{action&&<Pressable onPress={onAction} accessibilityRole="button"><Text style={s.link}>{action}</Text></Pressable>}</View>}
export function ProductCard({product,small=false}:{product:Product;small?:boolean}){const wish=useStore(x=>x.wishlist.includes(product.id));const toggle=useStore(x=>x.toggleWishlist);return <View style={[s.product,small&&{width:170}]}><View><ProductImage uri={product.images[0]} style={{width:'100%',aspectRatio:small?.82:0.84}}/><Pressable accessibilityRole="button" accessibilityLabel={wish?'Remove from wishlist':`Add ${product.name} to wishlist`} onPress={()=>toggle(product.id)} style={s.wish}><Ionicons name={wish?'heart':'heart-outline'} size={18} color={wish?colors.champagne:colors.ink}/></Pressable></View><Text style={s.meta}>{product.category.toUpperCase()}</Text><Text style={s.productName}>{product.name}</Text><Text style={s.price}>{money(product.price)}</Text></View>}
export function ProductRail({items}:{items:Product[]}){return <FlatList data={items} horizontal showsHorizontalScrollIndicator={false} keyExtractor={x=>x.id} renderItem={({item})=><ProductCard product={item} small/>} ItemSeparatorComponent={()=> <View style={{width:12}}/>} contentContainerStyle={{paddingRight:24}}/>}
export function Button({label,onPress,secondary=false}:{label:string;onPress:()=>void;secondary?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={[s.button,secondary&&s.buttonSecondary]}><Text style={[s.buttonText,secondary&&{color:colors.ink}]}>{label}</Text></Pressable>}
export function EmptyState({title,body,button,onPress}:{title:string;body:string;button:string;onPress:()=>void}){return <View style={s.empty}><Text style={s.h1}>{title}</Text><Text style={s.body}>{body}</Text><Button label={button} onPress={onPress} secondary/></View>}
export function Loading(){return <View style={s.loading}><ActivityIndicator color={colors.champagne}/></View>}
const s=StyleSheet.create({header:{height:60,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20,borderBottomWidth:1,borderBottomColor:colors.border,backgroundColor:colors.background},logo:{fontSize:13,letterSpacing:3,color:colors.ink},headerTitle:{fontFamily:'CormorantGaramond_500Medium',fontSize:22,color:colors.ink},icon:{padding:8},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline',marginBottom:14},h1:{...typography.h1,color:colors.ink},h2:{...typography.h2,color:colors.ink},body:{...typography.body,color:colors.muted},link:{fontSize:11,letterSpacing:1,color:colors.dark,textTransform:'uppercase'},product:{width:154},wish:{position:'absolute',right:8,top:8,backgroundColor:colors.surface,padding:7,borderRadius:20},meta:{fontSize:9,letterSpacing:1.2,color:colors.muted,marginTop:10},productName:{fontFamily:'Lora_400Regular',fontSize:13,color:colors.ink,marginTop:3},price:{fontFamily:'CormorantGaramond_500Medium',fontSize:17,color:colors.ink,marginTop:4},button:{height:50,backgroundColor:colors.dark,alignItems:'center',justifyContent:'center',paddingHorizontal:22,borderRadius:radii.sm},buttonSecondary:{backgroundColor:'transparent',borderWidth:1,borderColor:colors.border},buttonText:{color:colors.surface,fontSize:11,letterSpacing:1.2,textTransform:'uppercase'},empty:{alignItems:'center',padding:40,gap:12},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background}});
